from __future__ import annotations

from experiments.proposal_learning_loop import ProposalLearningConfig


LIVE_POLICY_VARIANTS = {
    "baseline": {
        "projection_margin_provisional": 0.0,
    },
    "targeted_gain_goal_proj_margin_01": {
        "projection_margin_provisional": 0.25,
    },
}


def build_default_config(*, verbose: bool = True) -> ProposalLearningConfig:
    cfg = ProposalLearningConfig(
        rounds=60,
        state_dim=12,
        comm_vocab_size=8,
        adapter_rank=4,
        adapter_alpha=0.5,
        use_world_model=True,
        wm_latent_dim=18,
        wm_hidden_dim=96,
        wm_lr=3e-4,
        wm_train_every=10,
        wm_batch_size=128,
        wm_min_replay=1024,
        wm_beta_kl=0.25,
        use_planning=True,
        plan_horizon=4,
        plan_candidates=24,
        plan_noise_std=0.6,
        plan_action_clip=3.0,
        pop_size=6,
        proposal_pop=0,
        sample_k=1,
        elites=0,
        mutation_std=0.0,
        immigrants=0,
        metrics_dim=32,
        proposal_hidden=128,
        proposal_scale=0.05,
        adopt_threshold=0.60,
        adopt_threshold_persistent=0.55,
        adopt_threshold_provisional=0.50,
        adopt_patch_l2_cost=0.0,
        self_improve_patch_l2_soft=0.40,
        self_improve_patch_l2_hard=0.55,
        self_improve_persistence_floor=0.02,
        self_improve_cooldown_bypass_streak=2,
        social_conf_activation="sigmoid",
        social_conf_activation_scale=1.25,
        social_conf_center=0.28,
        social_conf_weight_local=0.42,
        social_conf_weight_ma=0.18,
        social_conf_weight_streak=0.14,
        social_conf_weight_c2=0.10,
        social_conf_weight_c3=0.06,
        social_conf_weight_retained=0.14,
        social_conf_weight_sz=0.14,
        social_conf_provisional_patch_scale=0.35,
        adoption_score_threshold_provisional=0.47,
        adoption_score_threshold_full=0.58,
        adoption_score_activation="sigmoid",
        adoption_score_activation_scale=1.4,
        adoption_score_center=0.18,
        adoption_score_improve_weight=0.78,
        adoption_score_local_weight=0.18,
        adoption_score_projection_weight=0.06,
        adoption_score_projection_penalty_weight=0.34,
        adoption_score_recent_weight=0.12,
        adoption_score_credit_weight=0.08,
        adoption_score_patch_cost=0.08,
        adoption_score_goal_mse_weight=0.08,
        adoption_score_history_weight=0.24,
        adoption_score_instability_weight=0.12,
        adoption_score_improve_ref=0.15,
        adoption_score_local_ref=0.25,
        adoption_score_recent_ref=80.0,
        adoption_score_credit_ref=20.0,
        adoption_score_projection_ref=1.0,
        adoption_score_projection_soft=1.0,
        adoption_score_projection_hard=2.5,
        adoption_score_selection_conf_weight=0.45,
        adoption_score_selection_gain_weight=0.55,
        adoption_full_projection_error_max=1.35,
        wm_candidate_projection_enabled=True,
        wm_candidate_projection_horizon=5,
        wm_candidate_projection_samples=3,
        wm_candidate_projection_gamma=0.97,
        wm_candidate_projection_selection_weight=0.25,
        wm_candidate_pred_activation="sigmoid",
        wm_candidate_pred_activation_scale=1.6,
        wm_candidate_pred_center=0.04,
        wm_candidate_pred_gain_weight=0.45,
        wm_candidate_pred_projection_weight=0.18,
        wm_candidate_pred_instability_weight=0.14,
        wm_candidate_pred_risk_weight=0.17,
        wm_candidate_pred_uncertainty_weight=0.06,
        wm_candidate_pred_gain_ref=2.0,
        wm_candidate_pred_projection_ref=0.35,
        wm_candidate_pred_instability_ref=0.30,
        wm_candidate_pred_uncertainty_ref=0.75,
        wm_candidate_pred_score_threshold_full=0.55,
        wm_candidate_pred_score_threshold_selection=0.50,
        wm_candidate_pred_gain_min_full=0.10,
        wm_candidate_pred_projection_bad_max_provisional=0.72,
        wm_candidate_pred_projection_bad_max_full=0.44,
        wm_candidate_pred_rollback_risk_max_full=0.62,
        wm_candidate_pred_rollback_union_max_provisional=0.90,
        wm_candidate_pred_rollback_union_max_full=0.82,
        shadow_audit_enabled=True,
        shadow_audit_conf_margin=0.08,
        shadow_audit_gain_margin=0.08,
        shadow_audit_gain_wide_margin=0.25,
        shadow_audit_projection_bad_max=0.58,
        shadow_audit_patch_scale=0.35,
        shadow_audit_eval_salt=777,
        social_conf_full_local_min=0.10,
        social_conf_full_improvement_min=0.04,
        critical_entropy=2.0,
        steps_baseline=150,
        steps_dummy=120,
        verbose=verbose,
    )
    cfg.eval_kwargs = dict(
        self_gain=0.05,
        social_gain=0.02,
        noise_scale=0.01,
        msg_temp=1.0,
        speak_conf_threshold=0.55,
        message_cost_per_send=0.02,
        message_entropy_cost=0.02,
        w_familiarity=1.0,
        w_group_dev=1.0,
        w_pred_error=1.0,
        w_comm_entropy=0.8,
        w_comm_pe=0.6,
        curiosity_weight=0.05,
        curiosity_clip=5.0,
        goal_weight=0.10,
        goal_clip=10.0,
        debug_nan=False,
        log_telemetry=False,
        session_log_path="logs/consciousness_lab_session.log",
    )
    return cfg


def available_live_policy_variants() -> tuple[str, ...]:
    return tuple(LIVE_POLICY_VARIANTS.keys())


def apply_live_policy_variant(cfg: ProposalLearningConfig, variant_name: str) -> ProposalLearningConfig:
    variant_key = str(variant_name or "baseline")
    if variant_key not in LIVE_POLICY_VARIANTS:
        raise ValueError(f"Unknown live policy variant: {variant_key}")
    variant = dict(LIVE_POLICY_VARIANTS[variant_key])
    cfg.live_policy_variant = variant_key
    cfg.live_policy_projection_margin_provisional = float(variant.get("projection_margin_provisional", 0.0))
    return cfg
